### ISSUE TITLE
Inclusion of reply requirements.

### ISSUE THREAD

**Issue by Pircuremix** [Trimonu/TwitterAutoGiveawayBot#3]
For example in this tweet, 

$40 or 584rb Giveaway ~ 6 hrs 🛶

• RT this + Reply [#ToshibaTV](https://twitter.com/hashtag/ToshibaTV?src=hashtag_click) here
• Like, RT & Comment [#ToshibaTV](https://twitter.com/hashtag/ToshibaTV?src=hashtag_click) on the tweet below:

They tell the participant to specifically reply with the #ToshibaTV

**Comment by Trimonu** [comment]
Next update I'm releasing the ability for the bot to copy the most recent comment. Aprox 1-2 weeks.

**Comment by Trimonu** [comment]
I'll answer all future questions on the discord server https://discord.gg/RPArf67xSu
