### ISSUE TITLE
[Search method] httpx.get returns "404 not found"

### ISSUE THREAD

**Issue by SashelI** [Trimonu/TwitterAutoGiveawayBot#4]
Hi, 
This morning I've got this error while playing the code : 
![image](https://github.com/Trimonu/TwitterAutoGiveawayBot/assets/22128247/06a557e3-952b-4b92-afb3-96cee933e469)

The 404 errors happens when httpx.get tries to access to the adaptive search json from twitter api. Maybe they changed something ?

**Copy File**
`{"errors": [{"message": "Sorry, that page does not exist", "code": 34}]}`

 - OS: Windows 10 Pro
 - IDE: Spyder

Thanks !

**Comment by Trimonu** [comment]
Any idea on how many tweets you viewed today? Could be the new rate limiting

**Comment by SashelI** [comment]
Well the account I'm using to play with the bot isn't my main, so I've not seen any tweets since friday..

**Comment by Trimonu** [comment]
Ok a few things I want you to try
- Download the latest version
- Try on a different device
- Swap the search term
- Use a vpn
- Use a different Wi-Fi network
- Can you use twitter on the web app?
- Double check auth tokens

**Comment by SashelI** [comment]
I've tried all of this, same error. Don't you have it on your side ? 
The error comes from this line 
![image](https://github.com/Trimonu/TwitterAutoGiveawayBot/assets/22128247/852a76c7-ad19-48e3-901d-097e2decb196)

**Comment by Trimonu** [comment]
Based off what I've experienced with that error I think it's twitter blocking you. When I swap devices it usually works or giving it time.
If you really tried all the steps I mentioned I'm 99% sure you shouldn't be having issues.
If you tried all the steps message me on Discord @ "golx"

**Comment by Trimonu** [comment]
As I commented this someone else is having the same issue I'll take a look and check if they updated the API.

**Comment by Trimonu** [comment]
I'll answer all future questions on the discord server https://discord.gg/RPArf67xSu
