### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Romarikon** [Trimonu/TwitterAutoGiveawayBot#5]
**Describe the bug**
What is the error msg?

**Copy File**
Copy everything in the testData.json file

**Desktop (please complete the following information):**
 - OS: WINDOWS

![image](https://github.com/Trimonu/TwitterAutoGiveawayBot/assets/38276099/4f6ecc8d-675c-4e97-937c-d4657c56a3b5)

**Additional context**

**Comment by Trimonu** [comment]
Known error Twitter, shut down the api I was using. Will be fixed in next update.

**Comment by Pircuremix** [comment]
Any ETA on the next update? Curious on how you'll navigate the API change, if you're strapped for time I can commit the change if you point me in the right direction.

**Comment by Trimonu** [comment]
I'll answer all future questions on the discord server https://discord.gg/RPArf67xSu

**Comment by Trimonu** [comment]
I'll answer all future questions on the discord server https://discord.gg/RPArf67xSu
